### PR TITLE
Master

### PR DESCRIPTION
**Pull request by elizzard**

### CODE REVIEW

**Comment by gantih** [comment]
Hey liza,

Have u made any changes now ? I pulled your code at 10:30 in the morning
and started working on it. Let me know if u changed later so that i can
take the latest code

Regards,
Himaja

**Comment by elizzard** [comment]
Will do. Just got home, so no changes as of yet.
I will have a minor update of file_proc.cpp, in one of the functions that
will not affect any code in main().

**Comment by gantih** [comment]
I am merging all the files liza ... Just send me only the file u have
updated and what lines i will add them directly .. :)

Himaja

**Comment by elizzard** [comment]
no no, do not physically merge the my files into that..

Just #include "file_proc.h", comment out the main() in file_proc.cpp and
use the contents of main as described in comments.

Add all my files (except for README and test.txt) to your folder and g++
will link it.
The whole point of Git is so that you don't need to manually add any
collaborations. My change will not incur conflict with your code.  I will
be able to just merge it in.

Also see seattle u email chain.
- Liza

**Pull request merged**
